/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author 54265
 */
public class JFUniversidad extends javax.swing.JFrame {

    /**
     * Creates new form JFUniversidad
     */
    public JFUniversidad() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icono = new ImageIcon(getClass().getResource("/views/UniversidadULP.jpg"));
        Image miImagen = icono.getImage();
        jDesktopPane1 = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g){
                g.drawImage(miImagen,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMAlumno = new javax.swing.JMenu();
        jMIFormAlumno = new javax.swing.JMenuItem();
        jMMateria = new javax.swing.JMenu();
        jMIFormMateria = new javax.swing.JMenuItem();
        jMAdministracion = new javax.swing.JMenu();
        jMIInscripciones = new javax.swing.JMenuItem();
        jMINotas = new javax.swing.JMenuItem();
        jMConsultas = new javax.swing.JMenu();
        jMIAlumPorMat = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Universidad");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1292, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 856, Short.MAX_VALUE)
        );

        jMAlumno.setText("Alumno");

        jMIFormAlumno.setText("Formulario de Alumno");
        jMAlumno.add(jMIFormAlumno);

        jMenuBar1.add(jMAlumno);

        jMMateria.setText("Materia");

        jMIFormMateria.setText("Formulario de Materia");
        jMMateria.add(jMIFormMateria);

        jMenuBar1.add(jMMateria);

        jMAdministracion.setText("Administracion");

        jMIInscripciones.setText("Manejo de Inscripciones");
        jMIInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIInscripcionesActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMIInscripciones);

        jMINotas.setText("Manipulacion de Notas");
        jMINotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMINotasActionPerformed(evt);
            }
        });
        jMAdministracion.add(jMINotas);

        jMenuBar1.add(jMAdministracion);

        jMConsultas.setText("Consultas");
        jMConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMConsultasActionPerformed(evt);
            }
        });

        jMIAlumPorMat.setText("Alumnos por Materias");
        jMIAlumPorMat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMIAlumPorMatActionPerformed(evt);
            }
        });
        jMConsultas.add(jMIAlumPorMat);

        jMenuBar1.add(jMConsultas);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMIAlumPorMatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIAlumPorMatActionPerformed
        // TODO add your handling code here:
        JIFConsultas consultas = new JIFConsultas();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        int x = (jDesktopPane1.getWidth()/2) - (consultas.getWidth()/2);
        int y = (jDesktopPane1.getHeight()/2) - (consultas.getHeight()/2);
        consultas.setLocation(x, y);
        
        consultas.setVisible(true);
        jDesktopPane1.add(consultas);
        jDesktopPane1.moveToFront(consultas);
    }//GEN-LAST:event_jMIAlumPorMatActionPerformed

    private void jMConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMConsultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMConsultasActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMSalirMouseClicked

    private void jMINotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMINotasActionPerformed
        JIFNotas notas = new JIFNotas();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        int x = (jDesktopPane1.getWidth()/2) - (notas.getWidth()/2);
        int y = (jDesktopPane1.getHeight()/2) - (notas.getHeight()/2);
        notas.setLocation(x, y);
        
        notas.setVisible(true);
        jDesktopPane1.add(notas);
        jDesktopPane1.moveToFront(notas);
    }//GEN-LAST:event_jMINotasActionPerformed

    private void jMIInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMIInscripcionesActionPerformed
        // TODO add your handling code here:
        JIFInscripcion inscripciones = new JIFInscripcion();
        jDesktopPane1.removeAll();
        jDesktopPane1.repaint();
        
        int x = (jDesktopPane1.getWidth()/2) - (inscripciones.getWidth()/2);
        int y = (jDesktopPane1.getHeight()/2) - (inscripciones.getHeight()/2);
        inscripciones.setLocation(x, y);
        
        inscripciones.setVisible(true);
        jDesktopPane1.add(inscripciones);
        jDesktopPane1.moveToFront(inscripciones);
    }//GEN-LAST:event_jMIInscripcionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMAdministracion;
    private javax.swing.JMenu jMAlumno;
    private javax.swing.JMenu jMConsultas;
    private javax.swing.JMenuItem jMIAlumPorMat;
    private javax.swing.JMenuItem jMIFormAlumno;
    private javax.swing.JMenuItem jMIFormMateria;
    private javax.swing.JMenuItem jMIInscripciones;
    private javax.swing.JMenuItem jMINotas;
    private javax.swing.JMenu jMMateria;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
