package Views;

import Connection.AlumnoData;
import Connection.InscripcionData;
import Entidades.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class JIFInscripcion extends javax.swing.JInternalFrame {

    private DefaultTableModel model = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int a, int b) {

            return false;
        }
    };

    public JIFInscripcion() {
        initComponents();
        datos = new InscripcionData();
        datosalumnos = new AlumnoData();
        cargarCombo();
        armarCabecera();
        jrnoiscriptas.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jcalumnos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jrinscriptas = new javax.swing.JRadioButton();
        jrnoiscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtinscripcion = new javax.swing.JTable();
        jbinscripcion = new javax.swing.JButton();
        jbsalida = new javax.swing.JButton();
        jbanularinscripcion = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inscripciones");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Formulario de Inscripcion");

        jLabel3.setText("Seleccione un alumno:");

        jcalumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcalumnosActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Listado de Materias");

        jrinscriptas.setText("Materias Inscriptas");
        jrinscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrinscriptasActionPerformed(evt);
            }
        });

        jrnoiscriptas.setText("Materias no inscriptas");
        jrnoiscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrnoiscriptasActionPerformed(evt);
            }
        });

        jtinscripcion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtinscripcion);

        jbinscripcion.setText("Inscribir");
        jbinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbinscripcionActionPerformed(evt);
            }
        });

        jbsalida.setText("Salir");
        jbsalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalidaActionPerformed(evt);
            }
        });

        jbanularinscripcion.setText("Anular Inscripcion");
        jbanularinscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbanularinscripcionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jrinscriptas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jrnoiscriptas)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jbinscripcion)
                                        .addGap(73, 73, 73)
                                        .addComponent(jbanularinscripcion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jbsalida, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jcalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jLabel1)))
                        .addGap(16, 16, 16))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcalumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrnoiscriptas)
                    .addComponent(jrinscriptas))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbsalida)
                    .addComponent(jbanularinscripcion)
                    .addComponent(jbinscripcion))
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrinscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrinscriptasActionPerformed
        if (jrinscriptas.isSelected()) {
            jrnoiscriptas.setSelected(false);
        } else {
            jrnoiscriptas.setSelected(true);
        }
        jbinscripcion.setEnabled(false);
        jbanularinscripcion.setEnabled(true);

        borrarFilas();
        cargarFilas();
    }//GEN-LAST:event_jrinscriptasActionPerformed

    private void jbsalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalidaActionPerformed
        dispose();
    }//GEN-LAST:event_jbsalidaActionPerformed

    private void jcalumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcalumnosActionPerformed
        borrarFilas();
        cargarFilas();
    }//GEN-LAST:event_jcalumnosActionPerformed

    private void jbanularinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbanularinscripcionActionPerformed
        int fila = jtinscripcion.getSelectedRow();
        alumnoincribir = (Alumno) jcalumnos.getSelectedItem();
        inscripcion = new Inscripcion(alumnoincribir, materiaincribir, 0.00);
        datos.borrarInscripcionMateriaAlumno(alumnoincribir.getIdAlumno(), (int) jtinscripcion.getValueAt(fila, 0));
        borrarFilas();
        cargarFilas();
    }//GEN-LAST:event_jbanularinscripcionActionPerformed

    private void jbinscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbinscripcionActionPerformed
        int fila = jtinscripcion.getSelectedRow();
        materiaincribir = new Materia((int) jtinscripcion.getValueAt(fila, 0), jtinscripcion.getValueAt(fila, 1) + "", (int) jtinscripcion.getValueAt(fila, 2), true);
        alumnoincribir = (Alumno) jcalumnos.getSelectedItem();
        inscripcion = new Inscripcion(alumnoincribir, materiaincribir, 0.00);
        datos.guardarInscripcion(inscripcion);
        borrarFilas();
        cargarFilas();
    }//GEN-LAST:event_jbinscripcionActionPerformed

    private void jrnoiscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrnoiscriptasActionPerformed
        if (jrnoiscriptas.isSelected()) {
            jrinscriptas.setSelected(false);
        } else {
            jrinscriptas.setSelected(true);
        }
        jbinscripcion.setEnabled(true);
        jbanularinscripcion.setEnabled(false);

        borrarFilas();
        cargarFilas();
    }//GEN-LAST:event_jrnoiscriptasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbanularinscripcion;
    private javax.swing.JButton jbinscripcion;
    private javax.swing.JButton jbsalida;
    private javax.swing.JComboBox<Alumno> jcalumnos;
    private javax.swing.JRadioButton jrinscriptas;
    private javax.swing.JRadioButton jrnoiscriptas;
    private javax.swing.JTable jtinscripcion;
    // End of variables declaration//GEN-END:variables
    private List<Alumno> alumnos;
    private List<Materia> materias;
    private AlumnoData datosalumnos;
    private InscripcionData datos;
    private Inscripcion inscripcion;
    private Materia materiaincribir;
    private Alumno alumnoincribir;

    private void cargarCombo() {
        alumnos = datosalumnos.listarAlumnos();
        for (Alumno alu : alumnos) {
            jcalumnos.addItem(alu);
        }
    }

    private void armarCabecera() {

        model.addColumn("ID");
        model.addColumn("Nombre");
        model.addColumn("Año");
        jtinscripcion.setModel(model);
    }

    private void borrarFilas() {
        int f = model.getRowCount() - 1;
        for (; f >= 0; f--) {
            model.removeRow(f);
        }
    }

    private void cargarFilas() {
        Alumno uno = (Alumno) jcalumnos.getSelectedItem();
        if (jrinscriptas.isSelected()) {
            materias = datos.obtenerMateriasCursadas(uno.getIdAlumno());
        } else {
            materias = datos.obtenerMateriasNoCursadas(uno.getIdAlumno());
        }

        for (Materia mate : materias) {
            model.addRow(new Object[]{
                mate.getIdMateria(),
                mate.getNombre(),
                mate.getAnioMateria()
            });
        }

    }

}
